title: ownCloud Quickstart Guide
remote_theme: pmarsceill/just-the-docs
color_scheme: "nil"
search_enabled: true
description: Everything you need to install and configure ownCloud on CentOS. This QuickStart was fully tested on CentOS 8, package release 147.8.1.el8_1.
# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true
# Aux links for the upper right navigation
aux_links:
  "Aidan Reilly on GitHub":
    - "//github.com/aidanreilly"
# Footer content appears at the bottom of every page's main content
footer_content: "<a href = \"mailto:aidreilly@gmail.com\">Send me an email...</a>"


